### ISSUE TITLE
is there a way to get hubot to listen to all messages in a room not just when @<botname> mentioned? 

### ISSUE THREAD

**Issue by maxandersen** [gsuitedevs/hubot-google-hangouts-chat#14]
Reading #5 i'm confused if it will ever be possible for a bot to react to messages without its name mentioned.

Right now I can only seem to get messages sent with @<name> in a room - everything else is ignored. That makes log keeping and meeting notes bots and the likes hard to implement so i'm sure i'm missing something.

Reading https://developers.google.com/hangouts/chat/concepts/bots "Just like people, bots can participate in chat rooms, and they can respond to direct messages. But unlike people, bots only see messages directed to them when a person @mentions them in a chat room, or when a person sends them a direct message." 

if the above is the hard limitation I guess I answered my own question and it is not possible with google hangouts to make a bot that can i.e. convert a #5 to a github link or have short cuts, like ".meet start" rather than "@meetbot meet start" or be able to make a bot that will help transcribe and archive content.

Are my observations correct and there are no way around this ?

**Comment by sqrrrl** [comment]
Correct, it's currently not possible to observe other messages in a room. The Chat team might add that at some point in the future, but I'm not aware of an ETA for it.
