### ISSUE TITLE
How to run asynchronous queries via HTTP ? (where to set service accounts ?) 

### ISSUE THREAD

**Issue by bobman38** [gsuitedevs/hubot-google-hangouts-chat#2]
Hello

The adapter works pretty well for synchronous queries. But I am testing to use the ``robot.router.post`` method that allow asynchronous queries: 

In ``exemple.coffee``:
```
  robot.router.post '/hubot/chatsecrets/:room', (req, res) ->
    room   = req.params.room
    console.log req.body
    data   = req.body
    secret = data.secret

    robot.messageRoom room, "I have a secret: #{secret}"

    res.send 'OK'
```

And I have this result:

```
TypeError: Cannot read property 'thread' of undefined
  at HangoutsChatBot.sendMessage (/home/julien/web/hubot-google-hangouts-chat/src/bot.js:58:34)
  at HangoutsChatBot.send (/home/julien/web/hubot-google)hangouts-chat/src/bot.js:77:10)
  at Robot.messageRoom (/home/julien/web/myhubot/node_modules/hubot/src/robot.js:608:23)
  at /home/julien/web/myhubot/scripts/example.coffee:92:5, <js>:9:13
```

I assume that using HTTP mode we can only use today synchronous queries ([it post data using httpRes sent in the message](https://github.com/gsuitedevs/hubot-google-hangouts-chat/blob/master/src/bot.js#L55-L68)). Any option to have asynchronous ? :)

**Comment by rochejeremy** [comment]
Are cards supported when using pub/sub? Cards seem to work fine for webhooks, but I cannot get them to work with msg.send.

**Comment by rtilikay** [comment]
Hello, 

Asynchronous support has now been added. You will need to use a service account when making asynchronous queries. Please consult our documentation on how to set up a service account:

https://developers.google.com/hangouts/chat/how-tos/integrate-hubot#service_account
