### ISSUE TITLE
Are cards supported when using pub/sub? Cards seem to work fine for webhooks, but I cannot get them to work with msg.send.

### ISSUE THREAD

**Issue by kumarse** [gsuitedevs/hubot-google-hangouts-chat#4]
_Originally posted by @rochejeremy in https://github.com/gsuitedevs/hubot-google-hangouts-chat/issues/2#issuecomment-444693222_

**Comment by kumarse** [comment]
It should work fine with msg.send as well. Do you see any error messages?

Can you paste the card json that you are trying to send?

**Comment by rtilikay** [comment]
Sending cards is now supported by specifying the card JSON string as the second parameter to send or reply. Please see the cards.js example script on how to use this feature:

https://github.com/gsuitedevs/hubot-google-hangouts-chat/blob/master/examples/cards.js
