### ISSUE TITLE
Hubot doesn't react on direct messages when talking directly to him with @myhubot

### ISSUE THREAD

**Issue by daconstenla** [gsuitedevs/hubot-google-hangouts-chat#5]
Hi **all**, I've been playing around with hubot integration of hangouts chat and is not working is said in the documentation, according to it, hubot should answer back on any mention as:

```
MYHUBOT help
myhubot help
@myhubot help
myhubot: help
```
but with google chat integration bot only reacts when it's mentioned with `@` when it's mentioned twice, for example:
```
@myhubot myhubot help
```

after enabling `DEBUG=true` I've seen that in the received body is getting the `raw` message as `text` field but it's processing the field `argumentedText` which strips user's mention.

### possible solution

I've made a small change on the `HangoutsChatTextMessage` object creation to use received `message.text` and then it works as expected, any reason why on the implementation the object is being created with `argumentText`? I haven't seen any difference but mentioned removed from the message.

### raw json body of an example message with mention
```
...
        "text": "@myhubot help",
        "annotations": [
            {
                "type": "USER_MENTION",
                "startIndex": 0,
                "length": 8,
                "userMention": {
                    "user": {
                        "name": "users/USER-ID",
                        "displayName": "myhubot",
                        "avatarUrl": "https://lh4.googleusercontent.com/proxy/URL",
                        "type": "BOT"
                    },
                    "type": "MENTION"
                }
            }
        ],
        "thread": {
            "name": "spaces/THREAD-ID,
            "retentionSettings": {
                "state": "PERMANENT"
            }
        },
        "space": {
            "name": "spaces/SPACE-ID",
            "type": "ROOM",
            "displayName": "test-room"
        },
        "argumentText": " help"
...
```

Thanks!

**Comment by dgliu-f82** [comment]
@daconstenla were you trying this in a DM or Room?
In a room, Hangouts Chat doesn't invoke a bot unless it's explicitly @mention'ed by the user.
In a DM, every user message is sent to the bot since there's no other entity involved. 
message.text is the raw text from user and argumentText is raw text minus the @mention part. Therefore, argumentText is the correct one to use.

**Comment by joeyguerra** [comment]
I'm having the same problem. Perhaps I'm misunderstanding how this works. Should the regex pattern to match a handler include the bot's name in it? for example, if the bot name is `pipbot`, should the regex pattern to match handlers include `^\s*[@]?pipbot[:,]?\s*` in it?

**Comment by daconstenla** [comment]
@joeyguerra check the changes I made on the branch [issue-5](https://github.com/smava/hubot-google-hangouts-chat/tree/issue-5), by doing that, bot answers to my messages since message has the name of the bot on the message, otherwise is stripped from the message.

@dgliu-f82 I've tried with both approaches, DM's and Rooms, either way doesn't work as expected unless my change is applied.

**Comment by joeyguerra** [comment]
Yeah. Especially after reading this:
```  // Public: Adds a Listener that attempts to match incoming messages directed
  // at the robot based on a Regex. All regexes treat patterns like they begin
  // with a '^'
  //
  // regex    - A Regex that determines if the callback should be called.
  // options  - An Object of additional parameters keyed on extension name
  //            (optional).
  // callback - A Function that is called with a Response object.
  //
  // Returns nothing.
  respond (regex, options, callback) {
    this.hear(this.respondPattern(regex), options, callback)
  }
```

i believe using `text` instead of `argumentText` is correct. Because `text` will have the bot name included which is what the code expects for `respond` to work as designed.

**Comment by joeyguerra** [comment]
@daconstenla did you accept the code commit agreement? Gotta do that first.

**Comment by daconstenla** [comment]
I want to but since I did the contribution during working hours, I theoretically did the contribution as "company" and so I need my company to agree with the license before clicking the button 🤔

**Comment by joeyguerra** [comment]
maybe @daconstenla can make the change instead of your submitting a pull request then?

**Comment by joeyguerra** [comment]
maybe @dgliu-f82 can make the change instead of accepting the pull request then?

**Comment by dgliu-f82** [comment]
I believe the regex shouldn't contain the bot's name according to Hubot API. See the examples here:
https://hubot.github.com/docs/scripting/
The regex should match the user's message after the @mention part.

**Comment by joeyguerra** [comment]
Unfortunately, the code assumes that the bot's name is in the text. 

``` ^\s*[@]?pipbot[:,]?\s*```

gets prepended to the regex pattern that the scripts set (where `pipbot` is the name of the bot).

**Comment by dgliu-f82** [comment]
I see. I missed the difference between hear and respond earlier. For respond, Hubot automatically prepends the robot's name into the regex passed by the caller in order to match only messages directed at the bot. I think it does make sense for the Hangouts Chat adapter to pass the original text instead of argumentText. We will update the code shortly.

**Comment by joeyguerra** [comment]
Yeah, that's where the design of Hubot and integrations design of Google Chat are not congruent. Which is exactly what the Adapter Pattern is supposed to solve. And in this case, I feel like this module should adapt Google Chat's integration designs to conform to Hubots design.
